# NUMPY LEARNING

In [1]:
import numpy as np

Rank of an array- Number of dimensions in the array is called rank of the array

In [6]:
rank1array=np.array([0,1,2,3,4,5,6,7,8]) #rank1_array
print(rank1array,'Shape=',rank1array.shape,'Type',rank1array.dtype)
print('Class:',rank1array.__class__.__name__)

[0 1 2 3 4 5 6 7 8] Shape= (9,) Type int32
Class: ndarray


In [38]:
rank2array1=np.array([[0,1,2,3,4,5,6,7,8]]) #rank2_array
print('shape=',rank2array1.shape,'Type',rank2array1.dtype)

rank2array2=np.array([[0,1,2,3,4,5],[6,7,8,9,10,11],[12,13,14,15,16,17]]) #rank2
print('shape=',rank2array2.shape,'Type',rank2array1.dtype)

shape= (1, 9) Type int32
shape= (3, 6) Type int32


ndarray members

In [26]:
print('shape:',(rank2array2.shape))
print('Dimensions : ', rank2array2.ndim)
print('Number of elements : ', rank2array2.size)
print('Type : ', rank2array2.dtype)
print('1D array form:',rank2array2.flatten())
print('Transpose :\n ', rank2array2.T)

shape: (3, 6)
Dimensions :  2
Number of elements :  18
Type :  int32
1D array form: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
Transpose :
  [[ 0  6 12]
 [ 1  7 13]
 [ 2  8 14]
 [ 3  9 15]
 [ 4 10 16]
 [ 5 11 17]]


In [27]:
print('Reshape:',rank2array2.reshape(2,9))
print('Resize:',rank2array2.resize(2,10))

Reshape: [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]]
Resize: None


Rank 1 array indexing

In [36]:
print(rank1array)
print(rank1array[0])
print(rank1array[-1])
print(rank1array[1:3]) #start:end
print(rank1array[1:-1])
print(rank1array[1:])
print(rank1array[::2]) #step of 2
print(rank1array[1:6:2])
print(rank1array[::-1]) #reverse of an array
print(rank1array[8:1:-1])

[0 1 2 3 4 5 6 7 8]
0
8
[1 2]
[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7 8]
[0 2 4 6 8]
[1 3 5]
[8 7 6 5 4 3 2 1 0]
[8 7 6 5 4 3 2]


Rank2 array indexing

In [53]:
print(rank2array2,"\n")
print(rank2array2[1,],"\n")
print(rank2array2[1:2,0:2],"\n") #(rowstart:rowend, columnstart:columnend)
print(rank2array2[:,::-1],"\n") #reverse of each row
print(rank2array2[::-1,:]) #reverse order of each row

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]] 

[ 6  7  8  9 10 11] 

[[6 7]] 

[[ 5  4  3  2  1  0]
 [11 10  9  8  7  6]
 [17 16 15 14 13 12]] 

[[12 13 14 15 16 17]
 [ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]]


Np functions

Arange

In [62]:
print(np.arange(5),"\n")
print(np.arange(3,10),"\n")
print(np.arange(3,15,2),"\n")
print(np.arange(25).reshape(5,5))

[0 1 2 3 4] 

[3 4 5 6 7 8 9] 

[ 3  5  7  9 11 13] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Ones and zeros

In [76]:
print(np.zeros(4),"\n")
print(np.zeros((3,4)),"\n")
print(np.ones(3),"\n")
print(np.ones((3,2)),"\n")
print(np.ones(shape=(4,3,3,3)))

[0. 0. 0. 0.] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[1. 1. 1.] 

[[1. 1.]
 [1. 1.]
 [1. 1.]] 

[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]]


Repeat

In [80]:
newmatx=np.array([[2,3,4],[0,11,1],[2,2,6]])
print(np.repeat(newmatx,3,axis=0),"\n")
print(np.repeat(newmatx,3,axis=1))

[[ 2  3  4]
 [ 2  3  4]
 [ 2  3  4]
 [ 0 11  1]
 [ 0 11  1]
 [ 0 11  1]
 [ 2  2  6]
 [ 2  2  6]
 [ 2  2  6]] 

[[ 2  2  2  3  3  3  4  4  4]
 [ 0  0  0 11 11 11  1  1  1]
 [ 2  2  2  2  2  2  6  6  6]]


Concatination

In [83]:
newMatX = np.array([[2,3,4],[0,11,1],[2,2,6]])
newMatY = np.array([[1,1,1],[2,2,2],[3,3,3]])

print(np.concatenate((newMatX,newMatY), axis=0),"\n")
print(np.concatenate((newMatX,newMatY), axis=1))

[[ 2  3  4]
 [ 0 11  1]
 [ 2  2  6]
 [ 1  1  1]
 [ 2  2  2]
 [ 3  3  3]] 

[[ 2  3  4  1  1  1]
 [ 0 11  1  2  2  2]
 [ 2  2  6  3  3  3]]


Matrix Operation and linear algebra

In [93]:
matx=np.array([[2,3,4],[1,2,3],[2,1,1]])
maty=np.array([[1,7,4],[1,3,5],[3,8,0]])
I=np.identity(3)
#element wise multiplication
print('element wise',matx*I)
print(matx+I,"\n")
print(matx*I,"\n")

#matrix multiplication
print('matmul',np.matmul(matx,maty),"\n")

#Dot product
print('Dotprod',matx.dot(maty),"\n")

#Inverse of a matrix
print('Inverse',np.linalg.inv(maty))

#Determinant
print('determinant',np.linalg.det(maty))

#trace of a matrix
print('Trace',np.trace(matx),"\n")

#matrix raised to power
print('Raise',np.linalg.matrix_power(matx,3))


element wise [[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 1.]]
[[3. 3. 4.]
 [1. 3. 3.]
 [2. 1. 2.]] 

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 1.]] 

matmul [[17 55 23]
 [12 37 14]
 [ 6 25 13]] 

Dotprod [[17 55 23]
 [12 37 14]
 [ 6 25 13]] 

Inverse [[-0.6557377   0.52459016  0.37704918]
 [ 0.24590164 -0.19672131 -0.01639344]
 [-0.01639344  0.21311475 -0.06557377]]
determinant 61.000000000000064
Trace 5 

Raise [[ 88  98 129]
 [ 56  63  83]
 [ 47  51  67]]
